{"level":"info","message":"Server running in PRODUCTION environment","service":"vince-service","timestamp":"2024-04-05T22:35:03.756Z"}
{"level":"info","message":"Platform automation watcher is running","service":"vince-service","timestamp":"2024-04-05T22:35:03.790Z"}
{"level":"info","message":"This watcher will run every 1 hour","service":"vince-service","timestamp":"2024-04-05T22:35:03.791Z"}
{"level":"info","message":"Logger is ready","service":"vince-service","timestamp":"2024-04-05T22:35:03.791Z"}
{"level":"info","message":"Server started on port 4000 ðŸš€","service":"vince-service","timestamp":"2024-04-05T22:35:03.800Z"}
{"level":"info","message":"Server running in PRODUCTION environment","service":"vince-service","timestamp":"2024-04-05T23:04:16.860Z"}
{"level":"info","message":"Platform automation watcher is running","service":"vince-service","timestamp":"2024-04-05T23:04:16.904Z"}
{"level":"info","message":"This watcher will run every 1 hour","service":"vince-service","timestamp":"2024-04-05T23:04:16.905Z"}
{"level":"info","message":"Logger is ready","service":"vince-service","timestamp":"2024-04-05T23:04:16.905Z"}
{"level":"info","message":"Server started on port 4000 ðŸš€","service":"vince-service","timestamp":"2024-04-05T23:04:16.912Z"}
{"date":"Sat Apr 06 2024 01:05:17 GMT+0100 (West Africa Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"level":"error","message":"uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","os":{"loadavg":[1.9853515625,2.083984375,2.119140625],"uptime":90267},"process":{"argv":["/Users/mac/.nvm/versions/node/v16.20.2/bin/node","/Users/mac/Documents/nodejs_projects/future-vince-investment/backend/index.js"],"cwd":"/Users/mac/Documents/nodejs_projects/future-vince-investment/backend","execPath":"/Users/mac/.nvm/versions/node/v16.20.2/bin/node","gid":20,"memoryUsage":{"arrayBuffers":18445391,"external":20148281,"heapTotal":53526528,"heapUsed":49875408,"rss":65011712},"pid":30396,"uid":501,"version":"v16.20.2"},"service":"vince-service","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2024-04-06T00:05:17.455Z","trace":[]}
{"level":"info","message":"Server running in PRODUCTION environment","service":"vince-service","timestamp":"2024-04-07T21:50:40.876Z"}
{"level":"info","message":"Platform automation watcher is running","service":"vince-service","timestamp":"2024-04-07T21:50:40.934Z"}
{"level":"info","message":"This watcher will run every 1 hour","service":"vince-service","timestamp":"2024-04-07T21:50:40.934Z"}
{"level":"info","message":"Logger is ready","service":"vince-service","timestamp":"2024-04-07T21:50:40.935Z"}
{"level":"info","message":"Server started on port 4000 ðŸš€","service":"vince-service","timestamp":"2024-04-07T21:50:40.943Z"}
{"level":"info","message":"Server running in PRODUCTION environment","service":"vince-service","timestamp":"2024-04-07T22:00:33.072Z"}
{"level":"info","message":"Platform automation watcher is running","service":"vince-service","timestamp":"2024-04-07T22:00:33.123Z"}
{"level":"info","message":"This watcher will run every 1 hour","service":"vince-service","timestamp":"2024-04-07T22:00:33.123Z"}
{"level":"info","message":"Logger is ready","service":"vince-service","timestamp":"2024-04-07T22:00:33.124Z"}
{"level":"info","message":"Server started on port 4000 ðŸš€","service":"vince-service","timestamp":"2024-04-07T22:00:33.132Z"}
